schedules:
- cron: 36 13 08 * *
  displayName: Daily midnight build
  branches:
    include:
    - main
# NEW
trigger: none

pool: Ubuntu 

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
