22 15 * * *
20 15 Test_Pipline.yaml Test_Pipline.yaml Test_Pipline.yaml
task goes here
task goes here
# NEW
trigger: none

pool: Ubuntu

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
